### ISSUE TITLE
反斜杠路径变成文件名

### ISSUE THREAD

**Issue by Hanekihyouka** [teamsunset/DiscJockey#1]
操作系统：Arch Linux
启动器：Multimc
环境：在游玩 teacon 2023 整合包时出现

![Screenshot_2023-09-22_17-59-31_20230922192329.png](https://github.com/dsx137/DiscJockey/assets/44641661/aa766b50-d4ab-4be8-bc99-7695a7dab38c)

![Screenshot_2023-09-22_16-48-17_20230922192313.png](https://github.com/dsx137/DiscJockey/assets/44641661/36e404c6-1fa8-452d-90d4-ca4c0de98736)

路径变成文件名了，我猜这是意料外的，或许不应该使用反斜杠或者其转义。

**Comment by dsx137** [comment]
迷茫，明明这个问题已经修过一次了。应该是我的版本管理出错导致的。我想知道你的所有游戏文件都被删除了吗？因为我写了在游戏关闭时删除所有缓存

**Comment by dsx137** [comment]
> 操作系统：Arch Linux 启动器：Multimc 环境：在游玩 teacon 2023 整合包时出现
> 
> ![Screenshot_2023-09-22_17-59-31_20230922192329.png](https://user-images.githubusercontent.com/44641661/269922989-aa766b50-d4ab-4be8-bc99-7695a7dab38c.png)
> 
> ![Screenshot_2023-09-22_16-48-17_20230922192313.png](https://user-images.githubusercontent.com/44641661/269923012-36e404c6-1fa8-452d-90d4-ca4c0de98736.png)
> 
> 路径变成文件名了，我猜这是意料外的，或许不应该使用反斜杠或者其转义。

迷茫，明明这个问题已经修过一次了。应该是我的版本管理出错导致的。我想知道你的所有游戏文件都被删除了吗？因为我写了在游戏关闭时删除所有缓存

**Comment by dsx137** [comment]
迷茫，明明这个问题已经修过一次了。应该是我的版本管理出错导致的。我想知道你的所有游戏文件都被删除了吗？因为我写了在游戏关闭时删除所有缓存

**Comment by Hanekihyouka** [comment]
> 迷茫，明明这个问题已经修过一次了。应该是我的版本管理出错导致的。我想知道你的所有游戏文件都被删除了吗？因为我写了在游戏关闭时删除所有缓存

这些 mp3 文件与这个 cache 文件夹在同级目录，都在 .minecraft 目录下。
没有删除，这些文件还在。但如果向这个名为 "mods\discjockey\cache\\" 的文件夹内存放文件，存放的文件确实会被删除。

**Comment by Hanekihyouka** [comment]
[12f4030 ](https://github.com/dsx137/DiscJockey/commit/12f40308260346197771e552808874640790c86e) 后正常了。
